# torch `nn.Embedding`

## 사전학습된 임베딩을 사용하지 않는 경우

In [1]:
# 감성 분석 샘플 데이터
sentences = [
    'nice great best amazing',
    'stop lies',
    'pitiful nerd',
    'excellent work',
    'supreme quality',
    'bad',
    'highly respectable'
]
labels = [1, 0, 0, 1, 1, 0, 1]

In [2]:
# 토큰화
from nltk.tokenize import word_tokenize

tokenized_sentences = [word_tokenize(sent) for sent in sentences]
tokenized_sentences

[['nice', 'great', 'best', 'amazing'],
 ['stop', 'lies'],
 ['pitiful', 'nerd'],
 ['excellent', 'work'],
 ['supreme', 'quality'],
 ['bad'],
 ['highly', 'respectable']]

In [5]:
# 단어 사전/정수 인코딩
from collections import Counter

tokens = [token for sent in tokenized_sentences for token in sent]
word_counts = Counter(tokens)
print(word_counts)

word_to_index = {word: index + 2 for index, word in enumerate(tokens)}
word_to_index['<PAD>'] = 0
word_to_index['<UNK>'] = 1
word_to_index = dict(sorted(word_to_index.items(), key=lambda x:x[1]))
print(word_to_index)

vocab_size = len(word_to_index)
vocab_size

Counter({'nice': 1, 'great': 1, 'best': 1, 'amazing': 1, 'stop': 1, 'lies': 1, 'pitiful': 1, 'nerd': 1, 'excellent': 1, 'work': 1, 'supreme': 1, 'quality': 1, 'bad': 1, 'highly': 1, 'respectable': 1})
{'<PAD>': 0, '<UNK>': 1, 'nice': 2, 'great': 3, 'best': 4, 'amazing': 5, 'stop': 6, 'lies': 7, 'pitiful': 8, 'nerd': 9, 'excellent': 10, 'work': 11, 'supreme': 12, 'quality': 13, 'bad': 14, 'highly': 15, 'respectable': 16}

17

In [8]:
def texts_to_sequences(sentences, word_to_index):

    sequneces = []

    for sent in sentences:
        sequnece = []
        for token in sent:
            if token in word_to_index:
                sequnece.append(word_to_index[token])
            else:
                sequnece.append(word_to_index['<UNK>'])
        
        sequneces.append(sequnece)

    return sequneces

sequences = texts_to_sequences(tokenized_sentences, word_to_index)
sequences

[[2, 3, 4, 5], [6, 7], [8, 9], [10, 11], [12, 13], [14], [15, 16]]

In [9]:
# 패딩
import numpy as np

def pad_sequences(sequences, maxlen):
    padded_sqeunces = np.zeros((len(sequences), maxlen), dtype=int)
    for index, seq in enumerate(sequences):
        padded_sqeunces[index, :len(seq)] = seq[:maxlen]
    return padded_sqeunces

padded_sequences = pad_sequences(sequences, maxlen=4)
padded_sequences

array([[ 2,  3,  4,  5],
       [ 6,  7,  0,  0],
       [ 8,  9,  0,  0],
       [10, 11,  0,  0],
       [12, 13,  0,  0],
       [14,  0,  0,  0],
       [15, 16,  0,  0]])

In [10]:
# 모델 생성
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

class SimpleNet(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_size):
        super().__init__()
        self.embedding = nn.Embedding(
            num_embeddings=vocab_size,
            embedding_dim=embedding_dim,
            padding_idx=0   # 패딩 벡터는 학습하지 않음
        )
        self.rnn = nn.RNN(embedding_dim, hidden_size, batch_first=True)
        self.out = nn.Linear(hidden_size, 1)

    def forward(self, x):
        embedded = self.embedding(x)
        _, h_n = self.rnn(embedded)
        out = self.out(h_n.squeeze(0))
        return out
    
embedding_dim = 100
model = SimpleNet(vocab_size, embedding_dim, hidden_size=8)
model

SimpleNet(
  (embedding): Embedding(17, 100, padding_idx=0)
  (rnn): RNN(100, 8, batch_first=True)
  (out): Linear(in_features=8, out_features=1, bias=True)
)

In [11]:
import pandas as pd 

# 학습 전 임베딩 벡터
wv = model.embedding.weight.data
print(wv.shape)

# 특정 단어 벡터
vocab = word_to_index.keys()
pd.DataFrame(wv, index=vocab)

torch.Size([17, 100])

                   0         1         2   ...        97        98        99
<PAD>        0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
<UNK>        1.828872  0.509676 -0.288132  ... -1.140529  0.947225  0.263063
nice        -0.477682 -0.324669  0.173214  ...  0.523289 -0.335612 -0.443575
great        0.744822  0.027574 -0.421996  ... -1.283377  1.294117 -0.394892
best         0.376507 -0.120035 -0.166980  ...  0.871242 -1.112161  0.927057
amazing     -0.757098 -0.074299  0.291406  ...  0.245936 -0.191722 -1.000847
stop         1.290540  0.710814  0.466376  ...  0.420841 -0.042341  0.360928
lies        -0.510222 -1.838486 -1.179140  ... -0.815545 -0.270346  0.710555
pitiful     -0.823209  2.018602  0.883105  ...  0.650975  0.768749  0.170739
nerd         0.985166  0.128631 -0.317678  ... -0.900066  0.947356 -0.580533
excellent   -0.609500  0.959085  0.298561  ... -0.140897  1.425022  1.445673
work         0.398092  0.168814 -0.407838  ...  0.485553 -0.266331 -0.566615
supreme      0.981749  0.282829  0.709743  ...  0.061450 -1.947148  2.106804
quality      0.441806  1.563467 -0.572482  ... -0.560618  0.655945 -0.672889
bad          0.337398 -1.039142  0.615372  ... -0.009162  0.426578 -0.019133
highly       0.596803 -0.850522 -0.013797  ... -1.112206 -0.164452  1.459818
respectable  0.198403 -1.072099  1.642019  ...  0.539939  1.104343 -2.159919

[17 rows x 100 columns]

In [13]:
# 모델 학습
X = torch.tensor(padded_sequences, dtype=torch.long)            # (batch_size, seq_len)
y = torch.tensor(labels, dtype=torch.float).unsqueeze(1)        # (batch_size, 1)

print(f'{X.shape=}, {y.shape=}')

dataset = TensorDataset(X, y)
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

criterion = nn.BCEWithLogitsLoss()
optimizer = optim.Adam(model.parameters(), lr=0.005)

X.shape=torch.Size([7, 4]), y.shape=torch.Size([7, 1])

In [14]:
for epoch in range(20):

    epoch_loss = 0

    for x_batch, y_batch in dataloader:

        optimizer.zero_grad()
        output = model(x_batch)
        loss = criterion(output, y_batch)
        loss.backward()
        optimizer.step()

        epoch_loss += loss.item()

    print(f'Epoch {epoch+1} : Loss {epoch_loss / len(dataloader)}')

Epoch 1 : Loss 0.6598442494869232
Epoch 2 : Loss 0.5655427277088165
Epoch 3 : Loss 0.542184442281723
Epoch 4 : Loss 0.47659873217344284
Epoch 5 : Loss 0.45346350967884064
Epoch 6 : Loss 0.3899667337536812
Epoch 7 : Loss 0.3422394469380379
Epoch 8 : Loss 0.307168647646904
Epoch 9 : Loss 0.2530880756676197
Epoch 10 : Loss 0.21902861818671227
Epoch 11 : Loss 0.18650979921221733
Epoch 12 : Loss 0.15189366042613983
Epoch 13 : Loss 0.1311190463602543
Epoch 14 : Loss 0.12752268835902214
Epoch 15 : Loss 0.09968273714184761
Epoch 16 : Loss 0.09263269975781441
Epoch 17 : Loss 0.0851017776876688
Epoch 18 : Loss 0.06866804324090481
Epoch 19 : Loss 0.06136411055922508
Epoch 20 : Loss 0.058747841976583004

In [15]:
# 평가/예측
model.eval()
with torch.no_grad():
    output = model(X)
    prob = torch.sigmoid(output)
    pred = (prob >= 0.5).int()

print(labels)
print(pred.squeeze().detach().numpy())

[1, 0, 0, 1, 1, 0, 1]
[1 0 0 1 1 0 1]

In [16]:
# 학습 후 임베딩 벡터
wv = model.embedding.weight.data
print(wv.shape)

# 특정 단어 벡터
vocab = word_to_index.keys()
pd.DataFrame(wv, index=vocab)

torch.Size([17, 100])

                   0         1         2   ...        97        98        99
<PAD>        0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
<UNK>        1.828872  0.509676 -0.288132  ... -1.140529  0.947225  0.263063
nice        -0.431791 -0.344950  0.139104  ...  0.479077 -0.298619 -0.385998
great        0.775211 -0.007089 -0.465157  ... -1.315955  1.341755 -0.420812
best         0.409805 -0.156184 -0.134265  ...  0.815293 -1.079181  0.887403
amazing     -0.777900 -0.114637  0.333045  ...  0.211174 -0.232319 -1.039759
stop         1.231732  0.718791  0.443125  ...  0.383892 -0.099126  0.303743
lies        -0.566955 -1.788047 -1.115558  ... -0.767949 -0.341419  0.807691
pitiful     -0.812026  1.987920  0.923513  ...  0.638141  0.706346  0.258077
nerd         0.975523  0.129590 -0.265979  ... -0.863387  0.904838 -0.597722
excellent   -0.524368  1.019248  0.246684  ... -0.102133  1.498667  1.459956
work         0.452848  0.127877 -0.439207  ...  0.447382 -0.261612 -0.564850
supreme      0.913762  0.348780  0.690668  ...  0.123880 -1.962649  2.172040
quality      0.508129  1.503515 -0.563168  ... -0.615152  0.723221 -0.624688
bad          0.282456 -1.023995  0.720124  ... -0.037602  0.344013  0.015215
highly       0.696946 -0.896646 -0.169551  ... -1.130685 -0.063600  1.528292
respectable  0.305409 -1.113198  1.563036  ...  0.512177  1.200726 -2.195674

[17 rows x 100 columns]

## 사전학습된 임베딩을 사용하는 경우

https://code.google.com/archive/p/word2vec/

In [18]:
# 사전 학습 된 임베딩 로드
from gensim.models import KeyedVectors

model_wv = KeyedVectors.load_word2vec_format('GoogleNews-vectors-negative300.bin.gz', binary=True)
model_wv.vectors.shape

(3000000, 300)

In [ ]:
print(model_wv.most_similar('man', topn=5))
print(model_wv.most_similar('woman', topn=5))
print(model_wv.most_similar('king', topn=5))
print(model_wv.most_similar('queen', topn=5))

[('woman', 0.7664012908935547), ('boy', 0.6824871301651001), ('teenager', 0.6586930155754089), ('teenage_girl', 0.6147903203964233), ('girl', 0.5921714305877686)]
[('man', 0.7664012908935547), ('girl', 0.7494640946388245), ('teenage_girl', 0.7336829304695129), ('teenager', 0.6317085027694702), ('lady', 0.6288785934448242)]
[('kings', 0.7138045430183411), ('queen', 0.6510956883430481), ('monarch', 0.6413194537162781), ('crown_prince', 0.6204220056533813), ('prince', 0.6159993410110474)]
[('queens', 0.739944338798523), ('princess', 0.7070532441139221), ('king', 0.6510956883430481), ('monarch', 0.6383602023124695), ('very_pampered_McElhatton', 0.6357026696205139)]

In [20]:
print(model_wv.most_similar(positive=['king', 'woman'], negative=['man'], topn=5))
print(model_wv.most_similar(positive=['Paris', 'Italy'], negative=['France'], topn=5))

[('queen', 0.7118193507194519), ('monarch', 0.6189674139022827), ('princess', 0.5902431011199951), ('crown_prince', 0.5499460697174072), ('prince', 0.5377321839332581)]
[('Milan', 0.7222140431404114), ('Rome', 0.7028310298919678), ('Palermo_Sicily', 0.5967570543289185), ('Italian', 0.5911272764205933), ('Tuscany', 0.5632812976837158)]

In [22]:
# 모델의 Embedding layer에 초기화 할 embedding_matrix
print(len(word_to_index))   # (17, 300) 크기의 embedding_matrix 생성

embedding_matrix = np.zeros((len(word_to_index), model_wv.vectors.shape[1]))
print(embedding_matrix.shape)

17
(17, 300)

In [23]:
def get_word_embedding(word):
    if word in model_wv:
        return model_wv[word]
    else:
        return None
    
for word, index in word_to_index.items():
    if index >= 2:
        emb = get_word_embedding(word)
        if emb is not None:
            embedding_matrix[index] = emb

In [24]:
pd.DataFrame(embedding_matrix, index=word_to_index.keys())

                  0         1         2    ...       297       298       299
<PAD>        0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
<UNK>        0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
nice         0.158203  0.105957 -0.189453  ... -0.267578  0.008362 -0.213867
great        0.071777  0.208008 -0.028442  ... -0.167969 -0.020874 -0.142578
best        -0.126953  0.021973  0.287109  ... -0.101562 -0.090332  0.088379
amazing      0.073730  0.004059 -0.135742  ... -0.141602 -0.150391 -0.137695
stop        -0.057861  0.013184  0.115234  ...  0.086426  0.029907  0.007812
lies         0.149414 -0.012817  0.328125  ... -0.105469  0.149414  0.157227
pitiful      0.269531  0.253906 -0.020996  ... -0.072266 -0.094238  0.028809
nerd         0.265625 -0.207031 -0.026611  ...  0.124023 -0.030273  0.082031
excellent   -0.212891 -0.004303 -0.180664  ... -0.129883 -0.215820  0.012268
work        -0.075684  0.033691 -0.064941  ...  0.012024  0.135742 -0.091309
supreme      0.173828  0.172852  0.112793  ... -0.164062 -0.127930  0.097656
quality     -0.259766  0.271484  0.119629  ... -0.179688  0.000706 -0.014099
bad          0.062988  0.124512  0.113281  ... -0.063477  0.114746  0.031006
highly       0.050781 -0.227539 -0.130859  ... -0.056641  0.102539  0.074707
respectable  0.150391  0.285156 -0.023193  ... -0.200195 -0.112305  0.103027

[17 rows x 300 columns]